### ISSUE TITLE
コメントに〇〇分前、◯時間前といった時間を表示する

### ISSUE THREAD

**Issue by big-Miyabi** [team-essence/TAoSK#228]
# 概要
コメントは今デフォルトで99分前と表示するようになっているので修正する

下の通りに全く同じにしなくてはいいけど、実装する人がよしなにやろう！
タスクに表示する日付部分の処理が一部流用できそう

- 今日の変更の場合
  - mm分前
  - hh時間前
- 昨日の変更の場合
  - 昨日 hh:mm
- 一昨日より前の変更の場合
  - MM月DD日 hh:mm
- 一年以上前
  - YYYY年MM月DD日

**Comment by roll1226** [comment]
`utils`フォルダ内にある`date.ts`内の
```
  /**
   * format distance
   *
   * @static
   * @param {PropsDate} date
   * @return {string} [経過時間]
   * @memberof date
   */
  public static formatDistance = (date: PropsDate): string => {
    return formatDistanceToNow(new Date(date), { locale: ja })
  }
  ```
を使えばすぐ出来るはずやで
