### ISSUE TITLE
メンバーを横スクロールで動かないようにする

### ISSUE THREAD

**Issue by big-Miyabi** [team-essence/TAoSK#238]
# 概要

タスクをスクロールするとメンバー部分も含めてスクロールされてしまう

https://user-images.githubusercontent.com/47961006/146503598-90411443-91d3-46ce-a8df-4297d9052b91.mov

https://discord.com/channels/824955425983168553/909693628891406426/921294357108232193

**Comment by h-jun01** [comment]
TODOつけました💡

**Comment by big-Miyabi** [comment]
ウィンドウが拡大されていたのが原因でコード上に問題はなかったのでClose!
