### ISSUE TITLE
タスク一覧画面が重い

### ISSUE THREAD

**Issue by big-Miyabi** [team-essence/TAoSK#312]
# 概要
- subscriptionを導入してから特に重い
- #276 をやっても改善しなかった場合は対策を考える必要がある

## 考えられる原因
`useGetCurrentUserData` が原因な気がする
元々このhookは軽量で色々なとこで使い回していたが、そこにいきなりsubscriptionが入ってきて処理が膨大になったため、使い回した数だけ余分に処理が回っている可能性がある

subscripitonを使うhookを `useFetchSubscribedCurrentUserData`, 使わないhookを従来の`useGetCurrentUserData`にすれば多少は軽くなりそう

**Comment by roll1226** [comment]
これは完全に俺が無能すぎたのが悪いね、ごめん

**Comment by big-Miyabi** [comment]
@roll1226 いやいや、subscription実装するのにそこまで気回らないから仕方ないよｗ
むしろ面倒な処理やってくれてありがたい！
そこら辺の修正は俺らでも出来るしね

**Comment by roll1226** [comment]
@big-Miyabi 
ウィー
ただ、そこまでしっかり気を回せば天才プログラマになるから頑張らんと
