### ISSUE TITLE
プロジェクトに加わっていないユーザーもアサインできてしまう

### ISSUE THREAD

**Issue by big-Miyabi** [team-essence/TAoSK#313]
# 概要
プロジェクトに加わっていないユーザーもアサインできてしまう

実装時にプロジェクト作成時に使うユーザー検索のロジックを、タスクのユーザーアサインに使う検索機能に使ってしまっていたのが原因

APIから取得したgroupsから検索すれば実装可能なので修正する

https://discord.com/channels/824955425983168553/905979814031265793/924357117182378034

**Comment by roll1226** [comment]
取得してるgroupデータから検索出来ないかな？
当初の自分の想定だとそこから検索するもんだと思ってたからアサインで使うとは思ってなかった

**Comment by big-Miyabi** [comment]
@roll1226 あーなるほどな、そこに関してはAPIを介さずにフロント側で処理を行うのか
そうかuseSearchSameCompanyUsersMutationって命名だもんな、SameProjectじゃないもんな、気が付かなかったわごめん！

groupsから探せば実装可能なのね、やってみる。ありがと！
