### ISSUE TITLE
プロジェクト一覧の作成

### ISSUE THREAD

**Issue by big-Miyabi** [team-essence/TAoSK#75]
# 概要

プロジェクト一覧画面を作成する

# TODO
- [ ] uiフォルダ内にMonster関連のコンポーネントがあるが、これらはmodelsに移す

**Comment by roll1226** [comment]
[右側について](https://www.notion.so/11-28-6b9bc1808db845a081dfa8993956bb3b)

**Comment by roll1226** [comment]
ある程度完成
外部ディスプレイのサイズにも対応できるようリョーガちゃんが対応する

**Comment by roll1226** [comment]
- StyledProjectListContainer
- StyledProjectDetailContainer
↑の画像Path最初に`/`を入れ忘れておった
![すみません](https://photom.xyz/wp-content/uploads/2019/07/i000757_pandan_apology.png)
