### ISSUE TITLE
新規登録の横スクロールが若干できてしまう問題の修正

### ISSUE THREAD

**Issue by big-Miyabi** [team-essence/TAoSK#77]
# 概要
新規登録の横スクロールができてしまう問題を修正する

https://discord.com/channels/824955425983168553/909693628891406426/912942674112303144

## 発生環境
- 不明
  - Macbook Pro 13-inchi OS BigSur 11.6でChromeで検証から画面サイズを変えたり、大きめのディスプレイで表示したりと色々試したが、再現できなかった

**Comment by h-jun01** [comment]
原因不明すぎて困る
